steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'gs://exam_mlops_data_bucket', 'data/']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/exammlops/my-container/cloud',
    '-f',
    'dockerfiles/cloudtrain.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/exammlops/my-container/cloud'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
