# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main
#       - GithubActionCloudData
#   pull_request:
#     branches:
#       - main

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Authenticate with Google Cloud
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Set up gcloud
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           export_default_credentials: true

#       - name: Configure Docker for Google Cloud
#         run: |
#           gcloud auth configure-docker europe-west1-docker.pkg.dev

#       - name: Build Docker image
#         run: |
#           docker build -t europe-west1-docker.pkg.dev/$GCP_PROJECT_ID/my-container/cloudbuild:latest -f <path-to-dockerfile> .

#       - name: Push Docker image to GCP
#         run: |
#           docker push europe-west1-docker.pkg.dev/$GCP_PROJECT_ID/my-container/cloudbuild:latest
