name: "Flake8 testing"

on:
  push:
    branches:
      - main
      - LintingStep
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py
      - name: Flake test
        run: |
          pip install -r requirements_test.txt
          flake8 -v